name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Report success status  
    - uses: actions/github-script@v7
      with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       script: |
        github.repos.createStatus({
         owner: context.repo.owner,
         repo: context.repo.repo,
         sha: context.sha,
         state: "success",
         description: "Build succeeded",
         context: "continuous-integration/build"
        })
